<?php
$gerichte = [
    1 => ['g_name' => 'Bunter Gemüseauflauf mit Schmand und Käse überbacken dazu eine Scheibe Schwarzbrot',
        'i_preis' => '2.50',
        'e_preis' => '3.70',
        'bild' => '<img src="img/1.Gemüseauflauf.jpg" width="400" height="250">'],
    2 => ['g_name'=> 'Rinder eintopf mit Rotwein und südländischen Kräutern',
        'i_preis'=> '2.80',
        'e_preis'=> '3.90',
        'bild' => '<img src="img/2.Rinder eintopf.jpg" width="400" height="250">'],
    3=>['g_name'=> 'Fischeintopf mit geräuchteren Forellenfilet auf dampfendem Gemüse',
        'i_preis'=>'3.50',
        'e_preis'=>'4.20',
        'bild' => '<img src="img/3.Fischeintopf.jpg" width="400" height="250">'],
    4=>['g_name'=>'Heiße Käse tunke mit geschmolzenem Käse in Brotlaib serviert',
        'i_preis'=>'2.20',
        'e_preis'=>'3.10',
        'bild' => '<img src="img/4.Käse tunke.jpg" width="400" height="250">'],
    5=>['g_name'=>'Spaghetti mit Rind Frikadellen und scharfe Tomatensoße oder cremige Pilzen soße',
        'i_preis'=>'2.60',
        'e_preis'=>'3.5ß',
        'bild' => '<img src="img/5.Spaghetti mit Rind Frikadellen.jpg" width="400" height="250">'],
    6=>['g_name'=>'Bratkartoffel mit Wiener-schnitzel aus Schwein dazu Sauerkraut',
        'i_preis'=>'3.50',
        'e_preis'=>'4.20',
        'bild' => '<img src="img/6.Bratkartoffel mit Wiener-schnitzel.jpg" width="400" height="250">'],
    7=>['g_name'=>'Käsekuchen',
        'i_preis'=>'2.00',
        'e_preis'=>'2.70',
        'bild' => '<img src="img/7.Käsekuchen.jpg" width="400" height="250">'],
    8=>['g_name'=>'Schwarzwälder Kirschschnitt',
        'i_preis'=>'2.10',
        'e_preis'=>'2.80',
        'bild' => '<img src="img/8.Schwarzwälder Kirschschnitt.jpg" width="400" height="250">']
];
